services:
    jjb.formUtilsBundle.twig.extension.addJsConstraints:
        class: JJB\FormUtilsBundle\Twig\JSConstraintExtension
        arguments: [@jjb.formUtilsBundle.service.js_constraint]
        tags:
            - { name: twig.extension, alias: add_js_constraints }

    jjb.formUtilsBundle.service.js_constraint:
        class: JJB\FormUtilsBundle\Service\JSConstraintService
        arguments: [@translator.default]